{% set name = "svist4get" %}
{% set version = "1.2.14" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 6446ca147be050f25cd0c83f5633ad36f94a239cd9cee89cf8d3fb0b58902b84

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - argparse
    - biopython
    - configs
    - pip
    - pybedtools
    - python
    - reportlab
    - statistics
    - wand
  run:
    - argparse
    - biopython
    - configs
    - pybedtools
    - python
    - reportlab
    - statistics
    - wand

test:
  imports:
    - svist4get

about:
  home: "https://bitbucket.org/artegorov/svist4get/"
  license: WTFPL
  license_family: OTHER
  license_file: LICENSE
  summary: "A simple visualization tool for genomic tracks from sequencing experiments"
  doc_url: "https://bitbucket.org/artegorov/svist4get/"
  dev_url: "https://bitbucket.org/artegorov/svist4get/"

extra:
  recipe-maintainers:
    - jenzopr
